#!/usr/bin/env python
from naoqi import ALProxy

tts=ALProxy("ALTextToSpeech", "127.0.0.1", 9559)
motion = ALProxy("ALMotion", "127.0.0.1", 9559)
motion.moveInit()
id = motion.post.moveTo(0.5,0,0)
tts.say("Let's explore the area")
motion.wait(id,0)
tts.say("I have reached my destination")
